// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Team3.Backend.Data;

#nullable disable

namespace Team3.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912221435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Team3.Backend.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationalContentId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Team3.Backend.Models.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("Connections", t =>
                        {
                            t.HasCheckConstraint("CK_Connection_DifferentUsers", "\"UserAId\" <> \"UserBId\"");
                        });
                });

            modelBuilder.Entity("Team3.Backend.Models.ConnectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("ConnectionRequests");
                });

            modelBuilder.Entity("Team3.Backend.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EducationalContents");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContentInterest", b =>
                {
                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("EducationalContentId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("EducationalContentInterests");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContentLearningDirection", b =>
                {
                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearningDirectionId")
                        .HasColumnType("uuid");

                    b.HasKey("EducationalContentId", "LearningDirectionId");

                    b.HasIndex("LearningDirectionId");

                    b.ToTable("EducationalContentLearningDirections");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContentSkill", b =>
                {
                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("EducationalContentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EducationalContentSkills");
                });

            modelBuilder.Entity("Team3.Backend.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Team3.Backend.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningDirection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LearningDirections");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningDirectionInterest", b =>
                {
                    b.Property<Guid>("LearningDirectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("LearningDirectionId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("LearningDirectionInterests");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningDirectionSkill", b =>
                {
                    b.Property<Guid>("LearningDirectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("LearningDirectionId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("LearningDirectionSkills");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MeetingUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("LearningSessions");
                });

            modelBuilder.Entity("Team3.Backend.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationalContentId");

                    b.HasIndex("UserId", "EducationalContentId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Team3.Backend.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Team3.Backend.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Team3.Backend.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Team3.Backend.Models.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearningDirectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningDirectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("Team3.Backend.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearningSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RatedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RatedUserId");

                    b.HasIndex("RaterUserId");

                    b.HasIndex("LearningSessionId", "RaterUserId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Team3.Backend.Models.Repost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationalContentId");

                    b.HasIndex("UserId", "EducationalContentId")
                        .IsUnique();

                    b.ToTable("Reposts");
                });

            modelBuilder.Entity("Team3.Backend.Models.Save", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationalContentId");

                    b.HasIndex("UserId", "EducationalContentId")
                        .IsUnique();

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("Team3.Backend.Models.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EducationalContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationalContentId");

                    b.HasIndex("UserId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("Team3.Backend.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Team3.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LearningDirectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("LearningDirectionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Team3.Backend.Models.UserExperience", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ExperienceId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("UserExperiences");
                });

            modelBuilder.Entity("Team3.Backend.Models.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("Team3.Backend.Models.UserSkill", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("Team3.Backend.Models.Comment", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("Comments")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Connection", b =>
                {
                    b.HasOne("Team3.Backend.Models.User", "UserA")
                        .WithMany("ConnectionsAsUserA")
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "UserB")
                        .WithMany("ConnectionsAsUserB")
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("Team3.Backend.Models.ConnectionRequest", b =>
                {
                    b.HasOne("Team3.Backend.Models.User", "ReceiverUser")
                        .WithMany("ReceivedConnectionRequests")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "SenderUser")
                        .WithMany("SentConnectionRequests")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Team3.Backend.Models.Conversation", b =>
                {
                    b.HasOne("Team3.Backend.Models.Connection", "Connection")
                        .WithOne("Conversation")
                        .HasForeignKey("Team3.Backend.Models.Conversation", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContent", b =>
                {
                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("EducationalContents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContentInterest", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("EducationalContentInterests")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.Interest", "Interest")
                        .WithMany("EducationalContentInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContentLearningDirection", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("EducationalContentLearningDirections")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.LearningDirection", "LearningDirection")
                        .WithMany("EducationalContentLearningDirections")
                        .HasForeignKey("LearningDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("LearningDirection");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContentSkill", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("EducationalContentSkills")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.Skill", "Skill")
                        .WithMany("EducationalContentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningDirectionInterest", b =>
                {
                    b.HasOne("Team3.Backend.Models.Interest", "Interest")
                        .WithMany("LearningDirectionInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.LearningDirection", "LearningDirection")
                        .WithMany("LearningDirectionInterests")
                        .HasForeignKey("LearningDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("LearningDirection");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningDirectionSkill", b =>
                {
                    b.HasOne("Team3.Backend.Models.LearningDirection", "LearningDirection")
                        .WithMany("LearningDirectionSkills")
                        .HasForeignKey("LearningDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.Skill", "Skill")
                        .WithMany("LearningDirectionSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningDirection");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningSession", b =>
                {
                    b.HasOne("Team3.Backend.Models.Connection", "Connection")
                        .WithMany("LearningSessions")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Team3.Backend.Models.Like", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("Likes")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Message", b =>
                {
                    b.HasOne("Team3.Backend.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Team3.Backend.Models.Notification", b =>
                {
                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Profile", b =>
                {
                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Team3.Backend.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Progress", b =>
                {
                    b.HasOne("Team3.Backend.Models.LearningDirection", "LearningDirection")
                        .WithMany("Progresses")
                        .HasForeignKey("LearningDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningDirection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Rating", b =>
                {
                    b.HasOne("Team3.Backend.Models.LearningSession", "LearningSession")
                        .WithMany("Ratings")
                        .HasForeignKey("LearningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "RatedUser")
                        .WithMany("ReceivedRatings")
                        .HasForeignKey("RatedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "RaterUser")
                        .WithMany("GivenRatings")
                        .HasForeignKey("RaterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningSession");

                    b.Navigation("RatedUser");

                    b.Navigation("RaterUser");
                });

            modelBuilder.Entity("Team3.Backend.Models.Repost", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("Reposts")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Reposts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Save", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("Saves")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Saves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Share", b =>
                {
                    b.HasOne("Team3.Backend.Models.EducationalContent", "EducationalContent")
                        .WithMany("Shares")
                        .HasForeignKey("EducationalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("Shares")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.User", b =>
                {
                    b.HasOne("Team3.Backend.Models.LearningDirection", "LearningDirection")
                        .WithMany("Users")
                        .HasForeignKey("LearningDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningDirection");
                });

            modelBuilder.Entity("Team3.Backend.Models.UserExperience", b =>
                {
                    b.HasOne("Team3.Backend.Models.Experience", "Experience")
                        .WithMany("UserExperiences")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("UserExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.UserInterest", b =>
                {
                    b.HasOne("Team3.Backend.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.UserSkill", b =>
                {
                    b.HasOne("Team3.Backend.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team3.Backend.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Team3.Backend.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Team3.Backend.Models.Connection", b =>
                {
                    b.Navigation("Conversation");

                    b.Navigation("LearningSessions");
                });

            modelBuilder.Entity("Team3.Backend.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Team3.Backend.Models.EducationalContent", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EducationalContentInterests");

                    b.Navigation("EducationalContentLearningDirections");

                    b.Navigation("EducationalContentSkills");

                    b.Navigation("Likes");

                    b.Navigation("Reposts");

                    b.Navigation("Saves");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Team3.Backend.Models.Experience", b =>
                {
                    b.Navigation("UserExperiences");
                });

            modelBuilder.Entity("Team3.Backend.Models.Interest", b =>
                {
                    b.Navigation("EducationalContentInterests");

                    b.Navigation("LearningDirectionInterests");

                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningDirection", b =>
                {
                    b.Navigation("EducationalContentLearningDirections");

                    b.Navigation("LearningDirectionInterests");

                    b.Navigation("LearningDirectionSkills");

                    b.Navigation("Progresses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Team3.Backend.Models.LearningSession", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Team3.Backend.Models.Skill", b =>
                {
                    b.Navigation("EducationalContentSkills");

                    b.Navigation("LearningDirectionSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Team3.Backend.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ConnectionsAsUserA");

                    b.Navigation("ConnectionsAsUserB");

                    b.Navigation("EducationalContents");

                    b.Navigation("GivenRatings");

                    b.Navigation("Likes");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("Progresses");

                    b.Navigation("ReceivedConnectionRequests");

                    b.Navigation("ReceivedRatings");

                    b.Navigation("Reposts");

                    b.Navigation("Saves");

                    b.Navigation("SentConnectionRequests");

                    b.Navigation("Shares");

                    b.Navigation("UserExperiences");

                    b.Navigation("UserInterests");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
